import { NextResponse } from "next/server";
import crypto from "crypto";
import { App } from "@octokit/app";
import Groq from "groq-sdk";

export async function POST(req: Request) {
    // 1. Verify Webhook Signature
    const signature = req.headers.get("x-hub-signature-256");
    const event = req.headers.get("x-github-event");

    if (!signature || !event) {
        return NextResponse.json({ error: "Missing signature or event" }, { status: 400 });
    }

    const rawBody = await req.text();
    const secret = process.env.GITHUB_APP_WEBHOOK_SECRET || "";

    const hmac = crypto.createHmac("sha256", secret);
    const digest = "sha256=" + hmac.update(rawBody).digest("hex");

    if (signature !== digest) {
        return NextResponse.json({ error: "Invalid signature" }, { status: 401 });
    }

    const payload = JSON.parse(rawBody);

    // 2. We only care about pull requests being opened or synchronized (updated)
    if (event !== "pull_request" || !["opened", "synchronize", "reopened"].includes(payload.action)) {
        return NextResponse.json({ message: "Event ignored" });
    }

    // Check if installation exists in the payload
    if (!payload.installation || !payload.installation.id) {
        return NextResponse.json({ error: "No installation ID found" }, { status: 400 });
    }

    const installationId = payload.installation.id;
    const owner = payload.repository.owner.login;
    const repo = payload.repository.name;
    const pullNumber = payload.pull_request.number;
    const prTitle = payload.pull_request.title;

    try {
        // 3. Authenticate as the GitHub App Installation
        // The private key might have escaped newlines if loaded from some env configs
        let privateKey = process.env.GITHUB_APP_PRIVATE_KEY || "";
        if (privateKey.includes("\\n")) {
            privateKey = privateKey.replace(/\\n/g, "\n");
        }

        const app = new App({
            appId: process.env.GITHUB_APP_ID!,
            privateKey: privateKey,
        });

        const octokit = await app.getInstallationOctokit(installationId);

        // 4. Fetch the PR diff
        // Instead of downloading diff_url directly (which requires auth), use Octokit to get the diff.
        const diffResponse = await octokit.request("GET /repos/{owner}/{repo}/pulls/{pull_number}", {
            owner,
            repo,
            pull_number: pullNumber,
            headers: {
                accept: "application/vnd.github.v3.diff",
            },
        });

        let diffText = diffResponse.data as unknown as string;

        // Ensure diff is not insanely large (truncate to ~8000 chars as requested)
        if (diffText.length > 8000) {
            diffText = diffText.substring(0, 8000) + "\n...[DIFF TRUNCATED]...";
        }

        // 5. Send to Groq for analysis
        const groq = new Groq({
            apiKey: process.env.GROQ_API_KEY,
        });

        const systemPrompt = `You are a senior code reviewer. Review this pull request diff and provide:
1. Overall assessment (2-3 sentences)
2. Bugs or security issues found
3. Performance or code quality suggestions
4. What was done well
Be concise, specific, and actionable. Use markdown formatting.`;

        const chatCompletion = await groq.chat.completions.create({
            model: "llama-3.1-8b-instant",
            messages: [
                { role: "system", content: systemPrompt },
                { role: "user", content: `Here is the PR diff for '${prTitle}':\n\n${diffText}` }
            ],
            temperature: 0.3, // Lower temperature for more analytical/consistent reviews
            max_completion_tokens: 1500,
        });

        const reviewComment = chatCompletion.choices[0]?.message?.content;

        if (!reviewComment) {
            throw new Error("Failed to generate review from Groq.");
        }

        // 6. Post the comment back to the PR
        const signedComment = `${reviewComment}\n\n---\n*✨ Automated review generated by GRAM PR (Groq Llama 4).*`;

        await octokit.request("POST /repos/{owner}/{repo}/issues/{issue_number}/comments", {
            owner,
            repo,
            issue_number: pullNumber,
            body: signedComment,
        });

        return NextResponse.json({ success: true, message: "Review posted successfully!" });

    } catch (error: unknown) {
        console.error("Webhook processing error:", error);
        const err = error as Error;
        return NextResponse.json({ error: "Internal Server Error", details: err.message }, { status: 500 });
    }
}
